# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('omb_agency_code', models.CharField(blank=True, max_length=3)),
                ('omb_bureau_code', models.CharField(blank=True, max_length=2)),
                ('treasury_agency_code', models.CharField(blank=True, max_length=2)),
                ('cgac_agency_code', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
