# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cgac_agency_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='omb_agency_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='omb_bureau_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='treasury_agency_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
