# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160512_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['department', 'agency']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether or not the project is currently being worked on at 18F.'),
        ),
        migrations.AddField(
            model_name='project',
            name='billable',
            field=models.BooleanField(default=False, help_text='Whether or not the project is chargeable to a client.'),
        ),
        migrations.AddField(
            model_name='project',
            name='cloud_dot_gov',
            field=models.BooleanField(default=False, help_text='Whether or not the project includes cloud.govplatform support.'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='The GitHub URL of the project, e.g. https://github.com/18f/agile-bpa'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, help_text='The impact of the project. Markdown is allowed.'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_site_url',
            field=models.URLField(blank=True, help_text='A URL to the site where the project is deployed, if one exists.'),
        ),
        migrations.AddField(
            model_name='project',
            name='mb_number',
            field=models.CharField(blank=True, help_text='The unique identifier for an agreement inthe GSA financial system. This is different thanthe tock_id.', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, help_text='The slug of the project (e.g., "agile-bpa")', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, help_text='The tagline of the project; short and concise.', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='tock_id',
            field=models.IntegerField(blank=True, help_text='The ID of the project in Tock.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(help_text='The client of the project, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='The description of the project. Markdown is allowed.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='The full name of the project (e.g., "Agile BPA")', max_length=100),
        ),
    ]
