# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160514_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The client of the project, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Client'),
        ),
    ]
