# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160519_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='billable',
            field=models.IntegerField(choices=[(0, 'Billable'), (1, 'Non-billable')], default=1, help_text='Whether or not the project is chargeable to a non-18F client.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Tentative'), (1, 'Active'), (2, 'Paused'), (3, 'Complete')], default=1, help_text='Current status of the project.'),
        ),
    ]
