# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160519_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Projects with a primary private repos shouldbe listed as false. All other projects should be listed as true.', verbose_name='Is visible (in dashboard)?'),
        ),
    ]
