# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 10:45

"""
    For more details on this migration, see:

    https://github.com/18F/projects/issues/37
"""

from __future__ import unicode_literals

from django.db import migrations


BILLABLE = 0
NON_BILLABLE = 1

def convert_billable_to_boolean(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        if project.billable == BILLABLE:
            project.is_billable = True
        elif project.billable == NON_BILLABLE:
            project.is_billable = False
        else:
            raise Exception('%s billable is %s' % (project, project.billable))
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_is_billable'),
    ]

    operations = [
        migrations.RunPython(convert_billable_to_boolean,
                             reverse_code=migrations.RunPython.noop)
    ]
