# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_populate_is_billable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='billable',
        ),
    ]
